[package]
name = "CrossBuild"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
clap = "4.5.23"
dirs = "5.0.1"
reqwest = "0.12.11"
serde = "1.0.217"
serde_json = "1.0.134"
ssh2 = "0.9.4"
thiserror = "2.0.9"
tokio = "1.42.0"
